name: build & deploy pages

on:
  push:
    branches:
    - main

env:
  username: engureguo
  useremail: 57861661+engureguo@users.noreply.github.com
  ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "start!"

    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - run: echo 'yarn & yarn docs:build'

    - name: Build Front-end files
      run: |
        set -e
        yarn
        export NODE_OPTIONS=--openssl-legacy-provider
        yarn docs:build
    
    - name: Set up git env
      run: |
        git config --global init.defaultBranch main
        git config --global user.name "${{ env.username }}"
        git config --global user.email "${{ env.useremail }}"
        git remote set-url origin https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/$GITHUB_REPOSITORY

    - run: echo 'push gh-pages'

    - name: Push dist to gh-pages branch
      run: |
        cd docs/.vuepress/dist
        git init
        git add .
        git commit -m "Auto generated"
        git push -f main:gh-pages