name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.TOKEN_0214 }}
          TARGET_REPO: engureguo/engureguo.github.io
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: yarn && yarn docs:build
          BUILD_DIR: docs/.vuepress/dist
# name: vuepress build & deploy

# on:
#   push:
#     branches:
#     - main

# env:
#   username: engureguo
#   useremail: 57861661+engureguo@users.noreply.github.com
#   GITHUB_REPOSITORY: engureguo.github.io

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - run: echo "start!"

#     - uses: actions/checkout@v3

#     - name: Use Node.js
#       uses: actions/setup-node@v3
#       with:
#         node-version: '18.x'

#     - run: echo 'yarn & yarn docs:build'

#     - name: Build Front-end files
#       run: |
#         set -e
#         yarn
#         export NODE_OPTIONS=--openssl-legacy-provider
#         yarn docs:build

#     # - name: Set up git env
#     #   run: |
#     #     git config --global init.defaultBranch main
#     #     git config --global user.name "${{ env.username }}"
#     #     git config --global user.email "${{ env.useremail }}"
#     #     mkdir ~/.ssh &&  ${{ secrets.SSH_PRIVATE_KEY }} > ~/.ssh/id_rsa
#     #     tee ~/.ssh/config << "EOF"
#     #     Host github.com
#     #     HostName github.com
#     #     PreferredAuthentications publickey
#     #     IdentityFile ~/.ssh/id_rsa
#     #     EOF

#     # - run: echo 'push gh-pages'

#     # - name: Push dist to gh-pages branch
#     #   run: |
#     #     cd docs/.vuepress/dist
#     #     git init
#     #     git remote add origin git@github.com:engureguo/engureguo.github.io.git
#     #     git add .
#     #     git commit -m "Auto pushed"
#     #     git push -u origin main:gh-pages --force
