name: build & deploy pages

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Configure Git
      uses: actions/setup-git@v2
      with:
        git_user_name: engureguo
        git_user_email: 57861661+engureguo@users.noreply.github.com

    - name: Build Front-end files
      run: |
        yarn
        export NODE_OPTIONS=--openssl-legacy-provider
        yarn docs:build
        cd docs/.vuepress/dist
        git init
        git config --local user.email "${{ env.GIT_EMAIL }}"
        git config --local user.name "${{ env.GIT_NAME }}"
        git commit -a -m "Add changes"
        git push -f https://${{ secrets.ACCESS_TOKEN }}@github.com/engureguo/engureguo.github.io.git gh-pages
