name: build & deploy pages

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Build Front-end files
      run: |
        set -e
        yarn
        export NODE_OPTIONS=--openssl-legacy-provider
        yarn docs:build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: ./docs/.vuepress/dist
